---
kind: Service
apiVersion: v1
metadata:
  name: zeppelin-server    # keep Service name the same to Pod name.
  namespace: zeppelin
spec:
  ports:
    - name: http
      port: 80
    - name: rpc            # port name is referenced in the code. So it shouldn't be changed.
      port: 12320
  selector:
    app: zeppelin-server
