---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeppelin-server-notebook-volume
  namespace: zeppelin
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi

